version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 4VwY4oAou5T3trBHp1vZiAp1YG6LFZa3
      POSTGRES_DB: sms_uozd
      POSTGRES_USER: islam

    ports:
      - 5432:5432

  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://islam:4VwY4oAou5T3trBHp1vZiAp1YG6LFZa3@db:5432/sms_uozd
    ports:
      - '3000:3000'
